import { useState, useEffect, useRef, useCallback } from "react";
import { mockProducts, mockGoodsReceipts, GoodsReceipt, Product } from "@/lib/mock-data";
import { PackagePlus, Trash2, Search, ArrowLeft, ScanBarcode, X } from "lucide-react";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";
import { Html5Qrcode } from "html5-qrcode";
import { Input } from "@/components/ui/input";
import { motion, AnimatePresence } from "framer-motion";

const unitLabels: Record<string, string> = { piece: 'kom', kg: 'kg', meter: 'm', liter: 'L', box: 'kutija' };

const GoodsReceiptPage = () => {
  const navigate = useNavigate();
  const [receipts, setReceipts] = useState<GoodsReceipt[]>(mockGoodsReceipts);
  const [showForm, setShowForm] = useState(false);
  const [supplier, setSupplier] = useState("");
  const [note, setNote] = useState("");
  const [items, setItems] = useState<{ productId: string; productName: string; quantity: number; costPrice: number; sellingPrice: number; unit: string }[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [showSearch, setShowSearch] = useState(false);
  const [scanning, setScanning] = useState(false);
  const scannerRef = useRef<Html5Qrcode | null>(null);
  const filteredProducts = searchQuery.length > 0 ? mockProducts.filter(p => p.name.toLowerCase().includes(searchQuery.toLowerCase()) || p.sku.toLowerCase().includes(searchQuery.toLowerCase()) || p.barcode.includes(searchQuery)).slice(0, 5) : [];

  const addItem = (product: Product) => { const existing = items.find(i => i.productId === product.id); if (existing) { setItems(prev => prev.map(i => i.productId === product.id ? { ...i, quantity: i.quantity + 1 } : i)); toast.success(`${product.name} — količina povećana`); } else { setItems(prev => [...prev, { productId: product.id, productName: product.name, quantity: 1, costPrice: product.costPrice, sellingPrice: product.sellingPrice, unit: product.unit }]); toast.success(`${product.name} dodat u primku`); } setSearchQuery(""); setShowSearch(false); };
  const addItemByBarcode = (barcode: string) => { const product = mockProducts.find(p => p.barcode === barcode || p.sku === barcode); if (product) addItem(product); else toast.error("Proizvod nije pronađen", { description: barcode }); };
  const updateItem = (index: number, field: 'quantity' | 'costPrice' | 'sellingPrice', value: number) => { setItems(prev => prev.map((item, i) => i === index ? { ...item, [field]: value } : item)); };
  const removeItem = (index: number) => { setItems(prev => prev.filter((_, i) => i !== index)); };
  const totalCost = items.reduce((sum, i) => sum + i.quantity * i.costPrice, 0);
  const stopScanner = useCallback(async () => { if (scannerRef.current) { try { await scannerRef.current.stop(); scannerRef.current.clear(); } catch (e) {} scannerRef.current = null; } setScanning(false); }, []);
  const startScanner = useCallback(async () => { if (!showForm) setShowForm(true); setScanning(true); await new Promise(r => setTimeout(r, 400)); if (!document.getElementById("receipt-scanner")) return; try { const scanner = new Html5Qrcode("receipt-scanner"); scannerRef.current = scanner; await scanner.start({ facingMode: "environment" }, { fps: 15, qrbox: { width: 250, height: 150 }, aspectRatio: 1.333 }, (decodedText) => { addItemByBarcode(decodedText); }, () => {} ); } catch (err: any) { toast.error("Greška pri pokretanju kamere"); setScanning(false); } }, [showForm, items]);
  useEffect(() => { return () => { scannerRef.current?.stop().catch(() => {}); }; }, []);
  const handleSubmit = () => { if (!supplier.trim()) { toast.error("Unesite dobavljača"); return; } if (items.length === 0) { toast.error("Dodajte bar jedan artikal"); return; } const newReceipt: GoodsReceipt = { id: `gr${Date.now()}`, supplier: supplier.trim(), items: items.map(i => ({ productId: i.productId, productName: i.productName, quantity: i.quantity, costPrice: i.costPrice })), totalCost, date: new Date().toISOString(), note: note.trim() || undefined }; setReceipts([newReceipt, ...receipts]); setShowForm(false); setSupplier(""); setNote(""); setItems([]); stopScanner(); toast.success("Primka evidentirana"); };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3"><button onClick={() => navigate(-1)} className="p-1.5 text-muted-foreground"><ArrowLeft className="h-5 w-5" /></button><h1 className="text-xl font-bold text-foreground flex-1">Prijem robe</h1><button onClick={() => { setShowForm(!showForm); if (showForm) stopScanner(); }} className="flex items-center gap-1.5 px-3 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium"><PackagePlus className="h-4 w-4" />{showForm ? 'Zatvori' : 'Nova primka'}</button></div>
      {showForm && (
        <div className="bg-card border border-border rounded-xl p-4 space-y-3">
          <input type="text" value={supplier} onChange={e => setSupplier(e.target.value)} placeholder="Dobavljač *" className="w-full h-10 px-3 text-sm bg-secondary border border-border rounded-lg text-foreground placeholder:text-muted-foreground" />
          <input type="text" value={note} onChange={e => setNote(e.target.value)} placeholder="Napomena (opciono)" className="w-full h-10 px-3 text-sm bg-secondary border border-border rounded-lg text-foreground placeholder:text-muted-foreground" />
          <div className="relative bg-accent rounded-xl overflow-hidden">{scanning ? (<div className="relative"><div id="receipt-scanner" className="w-full" style={{ minHeight: 200 }} /><button onClick={stopScanner} className="absolute top-2 right-2 z-10 p-1.5 bg-background/80 backdrop-blur rounded-lg text-foreground"><X className="h-4 w-4" /></button></div>) : (<button onClick={startScanner} className="w-full flex items-center justify-center gap-2 py-6 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"><ScanBarcode className="h-6 w-6" /><span>Skeniraj barkod</span></button>)}</div>
          <div className="relative"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><input type="text" value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setShowSearch(true); }} onKeyDown={e => { if (e.key === 'Enter' && searchQuery.trim()) { addItemByBarcode(searchQuery.trim()); setSearchQuery(""); } }} placeholder="Pretraži ili unesi barkod..." className="w-full h-10 pl-9 pr-3 text-sm bg-secondary border border-border rounded-lg text-foreground placeholder:text-muted-foreground" /></div>{showSearch && filteredProducts.length > 0 && (<div className="absolute z-10 top-full left-0 right-0 mt-1 bg-card border border-border rounded-lg shadow-lg overflow-hidden">{filteredProducts.map(p => (<button key={p.id} onClick={() => addItem(p)} className="w-full flex items-center justify-between px-3 py-2.5 text-sm text-foreground hover:bg-secondary transition-colors"><div><span className="font-medium">{p.name}</span><span className="text-xs text-muted-foreground ml-2">Stanje: {p.stock}</span></div><span className="text-xs text-muted-foreground font-mono">{p.barcode || p.sku}</span></button>))}</div>)}</div>
          <AnimatePresence>{items.length > 0 && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-2"><p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Artikli ({items.length})</p>{items.map((item, i) => (<motion.div key={item.productId} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="bg-secondary/50 rounded-lg p-3 space-y-2"><div className="flex items-start justify-between"><p className="text-sm font-medium text-foreground flex-1 min-w-0 truncate">{item.productName}</p><button onClick={() => removeItem(i)} className="p-1 text-destructive shrink-0 ml-2"><Trash2 className="h-4 w-4" /></button></div><div className="grid grid-cols-3 gap-2"><div><label className="text-[10px] text-muted-foreground block mb-0.5">Količina</label><Input type="number" value={item.quantity} min={1} onChange={e => updateItem(i, 'quantity', Number(e.target.value))} className="h-8 text-xs text-center font-mono" /></div><div><label className="text-[10px] text-muted-foreground block mb-0.5">Nabavna (RSD)</label><Input type="number" value={item.costPrice} min={0} onChange={e => updateItem(i, 'costPrice', Number(e.target.value))} className="h-8 text-xs text-center font-mono" /></div><div><label className="text-[10px] text-muted-foreground block mb-0.5">Prodajna (RSD)</label><Input type="number" value={item.sellingPrice} min={0} onChange={e => updateItem(i, 'sellingPrice', Number(e.target.value))} className="h-8 text-xs text-center font-mono" /></div></div><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Marža: <span className="font-medium text-foreground">{item.costPrice > 0 ? ((item.sellingPrice - item.costPrice) / item.costPrice * 100).toFixed(0) : '—'}%</span></span><span className="font-mono">{(item.quantity * item.costPrice).toLocaleString('sr-RS')} RSD</span></div></motion.div>))}<div className="flex items-center justify-between pt-2 border-t border-border"><span className="text-sm font-medium text-foreground">Ukupna nabavka:</span><span className="text-sm font-bold text-foreground">{totalCost.toLocaleString('sr-RS')} RSD</span></div></motion.div>)}</AnimatePresence>
          <button onClick={handleSubmit} disabled={items.length === 0} className="w-full py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed">Evidentiraj primku ({items.length} artikala)</button>
        </div>
      )}
      <div className="space-y-2">{receipts.length > 0 && <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Prethodne primke</p>}{receipts.map(receipt => (<div key={receipt.id} className="bg-card border border-border rounded-xl p-4 space-y-2"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-foreground">{receipt.supplier}</p><p className="text-xs text-muted-foreground">{new Date(receipt.date).toLocaleString('sr-RS', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p></div><span className="text-sm font-bold text-foreground">{receipt.totalCost.toLocaleString('sr-RS')} RSD</span></div>{receipt.note && <p className="text-xs text-muted-foreground italic">{receipt.note}</p>}<div className="space-y-1">{receipt.items.map((item, i) => (<div key={i} className="flex items-center justify-between text-xs"><span className="text-foreground">{item.productName} × {item.quantity}</span><span className="text-muted-foreground font-mono">{(item.quantity * item.costPrice).toLocaleString('sr-RS')} RSD</span></div>))}</div></div>))}</div>
    </div>
  );
};

export default GoodsReceiptPage;